version: "3"

services:
  app:
    build: ./app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node src/server.js
    networks:
      - node-network
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    build: ./.docker/mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    ports:
      - "3306:3306"
    networks:
      - node-network

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    depends_on:
      - app
    ports:
      - "8080:80"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
